defaults:
  compute_nodes: 1
  cores_per_node: 2

tiers:
  - name: tier1
    capacity: 100.e+9
    max_bandwidth:
      read:
        seq: 200
        rand: 100
      write:
        seq: 100
        rand: 50

  - name: tier2
    capacity: 500.e+9
    max_bandwidth:
      read:
        seq: 500
        rand: 300
      write:
        seq: 200
        rand: 150

  - name: tier3
    capacity: 500.e+9
    bandwidth_model_path: "models/tier3_bandwidth.joblib"

  - name: tier4
    capacity: 500.e+9
    max_bandwidth: 800

ephemeral_tier:
  name: ephemeral
  capacity: 50.e+9
  max_bandwidth:
    read:
      seq: 500
      rand: 300
    write:
      seq: 200
      rand: 150
