# keycloak:
#   uri: https://localhost:18443
#   realm: atos-data-management
#   client: io-instrumentation

api:
    uri: http://kiwi0
    port: 8090

keycloak:
    uri: http://kiwi0
    port: 8080
    realm: atos-data-management
    client: io-instrumentation
